;;; codex-ide-model-tests.el --- Tests for Codex model metadata -*- lexical-binding: t; -*-

;;; Commentary:

;; Focused tests for model metadata exposed through app-server.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'codex-ide)

(ert-deftest codex-ide-reasoning-effort-options-use-model-list-metadata ()
  (cl-letf (((symbol-function 'codex-ide--available-models)
             (lambda (&optional _session)
               '(((id . "gpt-5.6-sol")
                  (model . "gpt-5.6-sol")
                  (supportedReasoningEfforts
                   . (((reasoningEffort . "low"))
                      ((reasoningEffort . "medium"))
                      ((reasoningEffort . "high"))
                      ((reasoningEffort . "xhigh"))
                      ((reasoningEffort . "max"))
                      ((reasoningEffort . "ultra"))))
                  (defaultReasoningEffort . "low")
                  (isDefault . t))))))
    (should (equal (codex-ide--reasoning-effort-options "gpt-5.6-sol")
                   '(:choices ("low" "medium" "high" "xhigh" "max" "ultra")
			      :default "low")))))

(ert-deftest codex-ide-reasoning-effort-options-use-default-model-for-empty-name ()
  (let ((codex-ide-model "gpt-5.4"))
    (cl-letf (((symbol-function 'codex-ide--available-models)
               (lambda (&optional _session)
                 '(((model . "gpt-5.4")
                    (supportedReasoningEfforts
                     . (((reasoningEffort . "medium"))))
                    (defaultReasoningEffort . "medium")
                    (isDefault . :json-false))
                   ((model . "gpt-5.6-sol")
                    (supportedReasoningEfforts
                     . (((reasoningEffort . "low"))))
                    (defaultReasoningEffort . "low")
                    (isDefault . t))))))
      (should (equal (codex-ide--reasoning-effort-options "")
                     '(:choices ("low") :default "low"))))))

(ert-deftest codex-ide-reasoning-effort-options-honor-default-model-session-override ()
  (let ((codex-ide-model "gpt-configured")
        (session (make-codex-ide-session)))
    (codex-ide-config-set-session-value 'model nil session)
    (codex-ide--session-metadata-put session :model-name "gpt-remembered")
    (cl-letf (((symbol-function 'codex-ide--available-models)
               (lambda (&optional _session)
                 '(((model . "gpt-default")
                    (supportedReasoningEfforts
                     . (((reasoningEffort . "low"))))
                    (defaultReasoningEffort . "low")
                    (isDefault . t))
                   ((model . "gpt-remembered")
                    (supportedReasoningEfforts
                     . (((reasoningEffort . "high"))))
                    (defaultReasoningEffort . "high")
                    (isDefault . :json-false))))))
      (should (equal (codex-ide--reasoning-effort-options nil session)
                     '(:choices ("low") :default "low"))))))

(ert-deftest codex-ide-reasoning-effort-options-use-remembered-session-model ()
  (let ((codex-ide-model nil)
        (session (make-codex-ide-session)))
    (codex-ide--session-metadata-put session :model-name "gpt-5.5")
    (cl-letf (((symbol-function 'codex-ide--available-models)
               (lambda (&optional captured-session)
                 (should (eq captured-session session))
                 '(((model . "gpt-5.6-sol")
                    (supportedReasoningEfforts
                     . (((reasoningEffort . "low"))))
                    (defaultReasoningEffort . "low")
                    (isDefault . t))
                   ((model . "gpt-5.5")
                    (supportedReasoningEfforts
                     . (((reasoningEffort . "medium"))
                        ((reasoningEffort . "high"))
                        ((reasoningEffort . "xhigh"))))
                    (defaultReasoningEffort . "medium")
                    (isDefault . :json-false))))))
      (should (equal (codex-ide--reasoning-effort-options nil session)
                     '(:choices ("medium" "high" "xhigh")
                       :default "medium"))))))

(ert-deftest codex-ide-reasoning-effort-options-prefer-configured-model ()
  (let ((codex-ide-model "gpt-configured")
        (session (make-codex-ide-session)))
    (codex-ide--session-metadata-put session :model-name "gpt-remembered")
    (cl-letf (((symbol-function 'codex-ide--available-models)
               (lambda (&optional _session)
                 '(((model . "gpt-default")
                    (supportedReasoningEfforts
                     . (((reasoningEffort . "low"))))
                    (defaultReasoningEffort . "low")
                    (isDefault . t))
                   ((model . "gpt-remembered")
                    (supportedReasoningEfforts
                     . (((reasoningEffort . "medium"))))
                    (defaultReasoningEffort . "medium")
                    (isDefault . :json-false))
                   ((model . "gpt-configured")
                    (supportedReasoningEfforts
                     . (((reasoningEffort . "high"))))
                    (defaultReasoningEffort . "high")
                    (isDefault . :json-false))))))
      (should (equal (codex-ide--reasoning-effort-options nil session)
                     '(:choices ("high") :default "high"))))))

(ert-deftest codex-ide-reasoning-effort-options-reject-unknown-or-missing-metadata ()
  (cl-letf (((symbol-function 'codex-ide--available-models)
             (lambda (&optional _session)
               '(((model . "gpt-5.6-sol")
                  (defaultReasoningEffort . "low")
                  (isDefault . t))))))
    (should-not (codex-ide--reasoning-effort-options "missing-model"))
    (should-not (codex-ide--reasoning-effort-options "gpt-5.6-sol"))))

(ert-deftest codex-ide-reasoning-effort-options-reject-unadvertised-default ()
  (cl-letf (((symbol-function 'codex-ide--available-models)
             (lambda (&optional _session)
               '(((model . "gpt-5.6-sol")
                  (supportedReasoningEfforts
                   . (((reasoningEffort . "low"))))
                  (defaultReasoningEffort . "ultra")
                  (isDefault . t))))))
    (should-not (codex-ide--reasoning-effort-options "gpt-5.6-sol"))))

(ert-deftest codex-ide-reasoning-effort-options-reject-malformed-efforts ()
  (dolist (efforts '(((reasoningEffort . "low"))
                     (((label . "Low")))
                     (((reasoningEffort . 1)))
                     (((reasoningEffort . "")))))
    (cl-letf (((symbol-function 'codex-ide--available-models)
               (lambda (&optional _session)
                 `(((model . "gpt-5.6-sol")
                    (supportedReasoningEfforts . ,efforts)
                    (defaultReasoningEffort . "low")
                    (isDefault . t))))))
      (should-not (codex-ide--reasoning-effort-options "gpt-5.6-sol")))))

(ert-deftest codex-ide-reasoning-effort-options-require-valid-default ()
  (dolist (default '(nil 1 ""))
    (cl-letf (((symbol-function 'codex-ide--available-models)
               (lambda (&optional _session)
                 `(((model . "gpt-5.6-sol")
                    (supportedReasoningEfforts
                     . (((reasoningEffort . "low"))))
                    (defaultReasoningEffort . ,default)
                    (isDefault . t))))))
      (should-not (codex-ide--reasoning-effort-options "gpt-5.6-sol")))))

(ert-deftest codex-ide-reasoning-effort-options-require-boolean-default-marker ()
  (let ((codex-ide-model nil))
    (cl-letf (((symbol-function 'codex-ide--available-models)
               (lambda (&optional _session)
                 '(((model . "gpt-5.6-sol")
                    (supportedReasoningEfforts
                     . (((reasoningEffort . "low"))))
                    (defaultReasoningEffort . "low")
                    (isDefault . "true"))))))
      (should-not (codex-ide--reasoning-effort-options "")))))

(ert-deftest codex-ide-reasoning-effort-options-require-valid-default-model-name ()
  (cl-letf (((symbol-function 'codex-ide--available-models)
             (lambda (&optional _session)
               '(((model . "")
                  (supportedReasoningEfforts
                   . (((reasoningEffort . "low"))))
                  (defaultReasoningEffort . "low")
                  (isDefault . t))))))
    (should-not (codex-ide--reasoning-effort-options ""))))

(ert-deftest codex-ide-available-model-names-reject-invalid-names ()
  (cl-letf (((symbol-function 'codex-ide--available-models)
             (lambda (&optional _session)
               '(((model . "gpt-valid"))
                 ((model . ""))
                 ((model . 42))
                 ((id . nil))))))
    (should (equal (codex-ide--available-model-names)
                   '("gpt-valid")))))

(ert-deftest codex-ide-available-models-cache-failures-within-one-interaction ()
  (dolist (result '(nil error))
    (let ((codex-ide--model-list-interaction-cache
           (make-hash-table :test #'equal))
          (fetch-count 0))
      (cl-letf (((symbol-function 'codex-ide--ensure-cli)
                 (lambda () t))
                ((symbol-function 'codex-ide--cleanup-dead-sessions)
                 (lambda () nil))
                ((symbol-function 'codex-ide--ensure-active-buffer-tracking)
                 (lambda () nil))
                ((symbol-function 'codex-ide--get-working-directory)
                 (lambda () "/tmp/codex-ide-model-cache/"))
                ((symbol-function
                  'codex-ide--query-session-for-thread-selection)
                 (lambda (&optional _directory) 'query-session))
                ((symbol-function 'codex-ide--list-models)
                 (lambda (&optional _session)
                   (setq fetch-count (1+ fetch-count))
                   (if (eq result 'error)
                       (error "model/list failed")
                     result))))
        (should-not (codex-ide--available-models))
        (should-not (codex-ide--available-models)))
      (should (= fetch-count 1)))))

(ert-deftest codex-ide-available-models-handle-working-directory-failure ()
  (cl-letf (((symbol-function 'codex-ide--get-working-directory)
             (lambda () (error "Working directory is unavailable"))))
    (should-not (codex-ide--available-models))))

(ert-deftest codex-ide-available-models-cache-is-request-and-directory-scoped ()
  (let ((directory "/tmp/codex-ide-model-cache-a/")
        (fetch-count 0))
    (cl-letf (((symbol-function 'codex-ide--ensure-cli)
               (lambda () t))
              ((symbol-function 'codex-ide--cleanup-dead-sessions)
               (lambda () nil))
              ((symbol-function 'codex-ide--ensure-active-buffer-tracking)
               (lambda () nil))
              ((symbol-function 'codex-ide--get-working-directory)
               (lambda () directory))
              ((symbol-function 'codex-ide--query-session-for-thread-selection)
               (lambda (&optional _directory) 'query-session))
              ((symbol-function 'codex-ide--list-models)
               (lambda (&optional _session)
                 (setq fetch-count (1+ fetch-count))
                 `(((model . ,directory))))))
      (let ((codex-ide--model-list-interaction-cache
             (make-hash-table :test #'equal)))
        (should (codex-ide--available-models))
        (setq directory "/tmp/codex-ide-model-cache-b/")
        (should (codex-ide--available-models)))
      (should (= fetch-count 2))
      (let ((codex-ide--model-list-interaction-cache
             (make-hash-table :test #'equal)))
        (should (codex-ide--available-models)))
      (should (= fetch-count 3)))))

(provide 'codex-ide-model-tests)

;;; codex-ide-model-tests.el ends here
